force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <label>Customer Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Gold__c.field-meta.xml
<CustomField>
    <fullName>Is_Gold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the field true when the customer clas if Gold for the first time.</description>
    <label>Is Gold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>Calculating the sum of Closed-Won Opportunities</description>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Twilio__c/Twilio__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store the Twilio authentication details for better use.</description>
    <label>Twilio Configuration</label>
</CustomObject>

force-app/main/default/objects/Twilio__c/fields/Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Account_SID__c</fullName>
    <description>Hold the Twilio Account SID</description>
    <label>Account SID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Holding the Twilio purchage number for sending notifications to the customers.</description>
    <label>Phone Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Holding the twilio tocken</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/TwilioURL__c.field-meta.xml
<CustomField>
    <fullName>TwilioURL__c</fullName>
    <description>holding the twilio URL</description>
    <label>TwilioURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>holding the Twilio version for the REST API</description>
    <label>Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEST_TwilioSendSMSAPI.cls
@IsTest
public class TEST_TwilioSendSMSAPI {
    
    @testsetup
    public static void loadData(){
        //Custom Setting test data
        Twilio__c twilio = new Twilio__c();
        twilio.Name='Test';
        twilio.Account_SID__c='35794835154';
        twilio.Phone_Number__c='+56982542345';
        twilio.Token__c='269340526';
        twilio.TwilioURL__c='https://abc.com';
        twilio.Version__c='3.2.0';
        insert twilio;
        
        List<Account> accListToInsert = new List<Account>();
        List<Opportunity> oppListToInsert = new List<Opportunity>();
        Account acc = new Account(AccountNumber='123435',Name='Test',Phone='+44 7776672865');
        
        Account acc1 = new Account(AccountNumber='123987',Name='Test1',Phone='51346890584');
    	accListToInsert.add(acc);
        accListToInsert.add(acc1);
        insert accListToInsert;
        
        Opportunity opp = new Opportunity(AccountId=acc.Id,Name='Test Opp1',CloseDate=Date.Today(),StageName='Prospecting', Amount=500000.0);
        Opportunity opp1 = new Opportunity(AccountId=acc.Id,Name='Test Opp2',CloseDate=Date.Today(),StageName='Prospecting', Amount=500000.0);
        
        Opportunity opp2 = new Opportunity(AccountId=acc1.Id,Name='Test Opp1',CloseDate=Date.Today(),StageName='Prospecting', Amount=30000.0);
        Opportunity opp3 = new Opportunity(AccountId=acc1.Id,Name='Test Opp2',CloseDate=Date.Today(),StageName='Prospecting', Amount=30000.0);
        
        oppListToInsert.add(opp);
        oppListToInsert.add(opp1);
        oppListToInsert.add(opp2);
        oppListToInsert.add(opp3);
        
        insert oppListToInsert;
    }
    
	@isTest
    public Static void TestSendSMSToGoldCustomerUpdate(){
        Account acc = [select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c,Phone,Name from Account where AccountNumber='123435' limit 1];
        
        List<Opportunity> opp = [select id,AccountId,Name,CloseDate,StageName,Amount from Opportunity where AccountId=:acc.Id];
        for(Opportunity o: opp){
        	o.StageName='Closed Won';
        }
        update opp;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        opp[0].Amount=2000;
        update opp[0];
        Account acc2 = [Select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c from Account where id=:acc.Id];
        
        System.assertEquals(True,acc2.Is_Gold__c);
        
        Test.stopTest();
    }
    
    @isTest
    public Static void SendSMSToGoldCustomerControllerTest(){
        Account acc = [select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c,Phone,Name from Account where AccountNumber='123435' limit 1];
        
        List<Opportunity> opp = [select id,AccountId,Name,CloseDate,StageName,Amount from Opportunity where AccountId=:acc.Id];
        for(Opportunity o: opp){
        	o.StageName='Closed Won';
        }
        update opp;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Account acc1 = [Select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c from Account where id=:acc.Id];
        
        System.assertEquals(True,acc1.Is_Gold__c);
        System.assertEquals('Gold',acc1.Customer_Classification__c);
        
        Test.stopTest();
    }
    
    @isTest
    public Static void SendSMSToGoldCustomerControllerTest1(){
        Account acc = [select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c,Phone,Name from Account where AccountNumber='123987' limit 1];
        
        List<Opportunity> opp = [select id,AccountId,Name,CloseDate,StageName,Amount from Opportunity where AccountId=:acc.Id];
        for(Opportunity o: opp){
        	o.StageName='Closed Won';
        }
        update opp;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Account acc1 = [Select id,Is_Gold__c,Customer_Classification__c,Total_Customer_Spend__c from Account where id=:acc.Id];
        
        System.assertNotEquals(True,acc1.Is_Gold__c);
        System.assertNotEquals('Gold',acc1.Customer_Classification__c);
        Test.stopTest();
    }

}