force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <label>Customer Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Gold__c.field-meta.xml
<CustomField>
    <fullName>Is_Gold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark the field true when the customer clas if Gold for the first time.</description>
    <label>Is Gold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>Calculating the sum of Closed-Won Opportunities</description>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Twilio__c/Twilio__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store the Twilio authentication details for better use.</description>
    <label>Twilio Configuration</label>
</CustomObject>

force-app/main/default/objects/Twilio__c/fields/Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Account_SID__c</fullName>
    <description>Hold the Twilio Account SID</description>
    <label>Account SID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Holding the Twilio purchage number for sending notifications to the customers.</description>
    <label>Phone Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Holding the twilio tocken</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/TwilioURL__c.field-meta.xml
<CustomField>
    <fullName>TwilioURL__c</fullName>
    <description>holding the twilio URL</description>
    <label>TwilioURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Twilio__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>holding the Twilio version for the REST API</description>
    <label>Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TwilioSendSMSAPI.cls
public class TwilioSendSMSAPI {
    
    public static void SendNotification(List<Account> accountList){
        List<Id> accountIds = new List<Id>();
        for(Account a: accountList){
            if(a.Customer_Classification__c=='Gold' && a.Is_Gold__c==true){
                accountIds.add(a.Id);
            }
        }
        if(accountIds.size()>0)
        	sendMessageNotificationToGoldPartners(accountIds,'null','null');
        
    }
    @future(callout=true)
    public static void sendMessageNotificationToGoldPartners(List<Id> accountIds,String msg,String phone){
        //Variable Declarations
        HttpRequest req = new HttpRequest();
        Http http = new Http();
        HTTPResponse res = new HTTPResponse();
        
    	//Query to get the Related Accounts Information
        List<Account> accountList = [select Id, Customer_Classification__c,Total_Customer_Spend__c,Phone,Name from Account where Id IN:accountIds];
        
        //Retrive the custom settings default values to build the REST API.
        Twilio__c twilio = Twilio__c.getInstance();
        //building the REST API endpoint.
        String endpoint = twilio.TwilioURL__c+twilio.Account_SID__c+'/SMS/Messages.json';
        
        //Creating a blob with AccountSId & Token
        Blob credentials = Blob.valueOf(twilio.Account_SID__c+':' + twilio.Token__c);
        
        req.setEndpoint(endPoint);
        req.setMethod('POST');//Using a Post method to send a Message Notification to the Customer
        
        //Preparing the Heders to Send REST callout to Twilio.
        req.setHeader('X-Twilio-Client', 'salesforce-' + twilio.Version__c);
        req.setHeader('User-Agent', 'twilio-salesforce/' + twilio.Version__c);
        req.setHeader('Accept', 'application/json');
        req.setHeader('Accept-Charset', 'utf-8');
        req.setHeader('Authorization', 'Basic '+EncodingUtil.base64Encode(credentials));
        
        for(Account a:accountList){
            if(a.Customer_Classification__c=='Gold' && a.Phone !=null){
                //Custom message notification like Your Account has been upgraded for the Opportunity Closed-Won
                String.format(System.Label.SMSNotification,  new List<Object>{ a.Name });
                
                //Preparing the REST API body and Provided the Phone Numbers. Here, By default I have provided the Phone Number from the Twilio Account. 
                //'+19302054108' this Number I purchanged in Twilio to Send All My Message notifications to the customer.
                if(phone!=null)
                	req.setBody('To=' + EncodingUtil.urlEncode(phone, 'UTF-8') + '&From=' + EncodingUtil.urlEncode(twilio.Phone_Number__c,'UTF-8') + '&Body=' + msg);
                else
                	req.setBody('To=' + EncodingUtil.urlEncode(a.Phone, 'UTF-8') + '&From=' + EncodingUtil.urlEncode(twilio.Phone_Number__c,'UTF-8') + '&Body=' + msg);
               
                system.debug(req);
                res = http.send(req);
            }
        }
        System.debug(res.getBody());

    }

}